### PR TITLE
Merge working json procedure call

### PR DESCRIPTION
**Pull request by rachittibrewal**
The PR aims to merge the RPC using json over websockets.

The boost beast library has been checked in due to usage of boost/beast/experimental/core/ssl_stream.hpp
which is absent in the version pulled by hunter (boost 1.66!).

### CODE REVIEW

**Comment by jlblancoc** [comment]
cc: @jolting 
Does including the full boost/asio make sense here?

**Comment by rachittibrewal** [comment]
@jlblancoc thanks for pointing that out I removed asio from the include dir and still it works fine.

**Comment by jolting** [comment]
Thanks for fixing that. The Hunter package manager is perfectly capable of fetching a specific version of boost to link against. Beast is included in all versions of boost after 1.66

**Comment by rachittibrewal** [comment]
@jolting I have made changes to CWebSocketAdvanced.h so now don't need to check beast into the repo.

**Pull request merged**
